version: "3.0"
services:
  soap-service:
    container_name: soap-jax-ws
    build: .
    ports:
      - "8001:8001"
    env_file: .env
    volumes:
      - ./:/app
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - soap-network
  mysql:
    container_name: db-soap
    image: mysql:latest
    ports:
      - "3308:3306"
    env_file: .env
    hostname: db-soap
    volumes:
      - ./db:/var/lib/mysql
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      interval: 10s
      timeout: 3s
      retries: 5      
    networks:
      - soap-network
volumes:
  db:
    driver: local
networks:
  soap-network:
    driver: bridge
