version: "3.0"
services:
  cooklyst-soap-service:
    build: .
    ports:
      - "8001:8001"
    env_file: .env
    volumes:
      - ./:/app
    depends_on:
      cooklyst-soap-db:
        condition: service_healthy

    # COMMENT THIS IF YOU USE DOCKER CONFIG TO START ALL CONTAINERS
    networks:
      - soap-network

  cooklyst-soap-db:
    image: mysql:latest
    ports:
      - "3308:3306"
    env_file: .env
    hostname: cooklyst-soap-db
    volumes:
      - ./db:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      interval: 10s
      timeout: 3s
      retries: 5

    # COMMENT THIS IF YOU USE DOCKER CONFIG TO START ALL CONTAINERS
    networks:
      - soap-network

volumes:
  db:
    driver: local
# COMMENT THIS IF YOU USE DOCKER CONFIG TO START ALL CONTAINERS
networks:
  soap-network:
    driver: bridge
